### ISSUE TITLE
_tkinter module not included with Python 3.11 manylinux2014

### ISSUE THREAD

**Issue by marcelotduarte** [pypa/manylinux#1460]
I'm using manylinux2014 to generate wheels for cx_Freeze (and Tkinter is a must #1365).

Tested with:
```
$ docker image list
REPOSITORY                          TAG                  IMAGE ID       CREATED       SIZE
quay.io/pypa/manylinux2014_x86_64   latest               936af5da0a5a   3 days ago    1.3GB
quay.io/pypa/manylinux2014_x86_64   2023-01-14-103cb93   bc44454907bd   6 weeks ago   1.3GB
quay.io/pypa/musllinux_1_1_x86_64   2023-01-14-103cb93   c8c4530e3a8c   6 weeks ago   855MB
$ docker run --rm -ti quay.io/pypa/manylinux2014_x86_64
[root@3195538433df /]# /opt/python/cp311-cp311/bin/python
Python 3.11.2 (main, Feb 26 2023, 21:43:07) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python/cp311-cp311/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
>>> ^D
[root@3195538433df /]# ll /opt/python/cp3*-cp3*/lib/python3.*/lib-dynload/_tkinter.cpython-3*-x86_64-linux-gnu.so
-rwxr-xr-x 1 root root 66576 Feb 26 21:46 /opt/python/cp310-cp310/lib/python3.10/lib-dynload/_tkinter.cpython-310-x86_64-linux-gnu.so
-rwxr-xr-x 1 root root 63104 Feb 26 21:44 /opt/python/cp36-cp36m/lib/python3.6/lib-dynload/_tkinter.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x 1 root root 63104 Feb 26 21:45 /opt/python/cp37-cp37m/lib/python3.7/lib-dynload/_tkinter.cpython-37m-x86_64-linux-gnu.so
-rwxr-xr-x 1 root root 65216 Feb 26 21:45 /opt/python/cp38-cp38/lib/python3.8/lib-dynload/_tkinter.cpython-38-x86_64-linux-gnu.so
-rwxr-xr-x 1 root root 65216 Feb 26 21:46 /opt/python/cp39-cp39/lib/python3.9/lib-dynload/_tkinter.cpython-39-x86_64-linux-gnu.so
[root@3195538433df /]# 
```
With musllinux_1_1_x86_64 it is ok.

**Comment by marcelotduarte** [comment]
I found a change in python configure at https://github.com/python/cpython/commit/b36d222110d0d6d84dc8e973ca87d976c2423f5d
