### ISSUE TITLE
auditwheel crash on current image

### ISSUE THREAD

**Issue by whs** [pypa/manylinux#230]
The auditwheel command does not work on the current image (`quay.io/pypa/manylinux1_x86_64@sha256:7967d9758d679ce31d0c314a24752550bc41c612b35e07d9f4ce42ed898c165e`)

```
[root@4bfc75c75596 wheelhouse]# auditwheel show protobuf-3.6.1-py2.py3-none-any.whl
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 11, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/main.py", line 49, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/main_show.py", line 22, in execute
    from .wheel_abi import analyze_wheel_abi
  File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/wheel_abi.py", line 9, in <module>
    from .genericpkgctx import InGenericPkgCtx
  File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/genericpkgctx.py", line 1, in <module>
    from .wheeltools import InWheelCtx
  File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/wheeltools.py", line 14, in <module>
    from wheel.util import urlsafe_b64encode, open_for_csv, native  # type: ignore
ImportError: cannot import name 'open_for_csv'
```

**Comment by whs** [comment]
Seems to be due to https://github.com/pypa/auditwheel/issues/102 . Waiting on that issue to be fixed and new image released.

**Comment by whs** [comment]
Should be fixed by https://github.com/pypa/manylinux/pull/229

**Comment by trishankatdatadog** [comment]
Sorry, guys, my bad, next time I should leave package updates sitting for a
while unless there are CVEs to be fixed

**Comment by njsmith** [comment]
No way, the fault is in our process and tools, not you. There's no
particular reason to think that waiting would have helped, even, and it got
sorted out quickly anyway. Going down the road towards vague guilt and
vague inefficient rituals won't help anyone.

**Comment by matthew-brett** [comment]
Yes, seconded - there wasn't any easy way to know what was going to happen here.

Having said that, it might be worth adding a policy of holding off on tool updates for a bit.

**Comment by sidarthagracias** [comment]
Do we know when a new image might come out. It seems like since the only images published is "latest" which gets overwritten, we don't have access to an old good image. Is that correct, do we just have to wait for the next image to come out?
