### ISSUE TITLE
Auditwheel fail for python3.6 - cannot import name 'open_for_csv'

### ISSUE THREAD

**Issue by ikus060** [pypa/manylinux#336]
Using manylinux2010 image, our build is failing as follow:
```
$ auditwheel repair dist/*.whl
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 10, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.6.9/lib/python3.6/site-packages/auditwheel/main.py", line 50, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.6.9/lib/python3.6/site-packages/auditwheel/main_repair.py", line 49, in execute
    from .repair import repair_wheel
  File "/opt/_internal/cpython-3.6.9/lib/python3.6/site-packages/auditwheel/repair.py", line 14, in <module>
    from .wheeltools import InWheelCtx, add_platforms
  File "/opt/_internal/cpython-3.6.9/lib/python3.6/site-packages/auditwheel/wheeltools.py", line 15, in <module>
    from wheel.util import urlsafe_b64encode, open_for_csv, native  # type: ignore
ImportError: cannot import name 'open_for_csv'
ERROR: Job failed: exit code 1
```

**Comment by ikus060** [comment]
Never mind, I found the issue. Some script was updating the "wheel" package instead of keeping the version installed in the manylinux image.

Closing as invalid.
