### ISSUE TITLE
docker image manylinux2010_x86_64 yum error undefined symbol: CRYPTO_set_locking_callback

### ISSUE THREAD

**Issue by levyfan** [pypa/manylinux#416]
```
[root@c21dbc793d27 /]# python
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/yum/__init__.py", line 53, in <module>
    import config
  File "/usr/lib/python2.6/site-packages/yum/config.py", line 30, in <module>
    from parser import ConfigPreProcessor, varReplace
  File "/usr/lib/python2.6/site-packages/yum/parser.py", line 4, in <module>
    import urlgrabber
  File "/usr/lib/python2.6/site-packages/urlgrabber/__init__.py", line 54, in <module>
    from grabber import urlgrab, urlopen, urlread
  File "/usr/lib/python2.6/site-packages/urlgrabber/grabber.py", line 434, in <module>
    import pycurl
ImportError: /usr/lib64/python2.6/site-packages/pycurl.so: undefined symbol: CRYPTO_set_locking_callback
>>> 
```

The installed pycurl.so linked to `/usr/local/lib/libcurl.so.4`, which does not link to libssl and libcrypto. The correct linking should be `/usr/lib64/libcurl.so.4`.

```
[root@c21dbc793d27 /]# ldd /usr/lib64/python2.6/site-packages/pycurl.so
        linux-vdso.so.1 =>  (0x00007fff822f9000)
        libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007f0ad6cd0000)
        libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x00007f0ad692a000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0ad670d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f0ad6379000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f0ad6163000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f0ad5f5b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0ad5d57000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f0ad5b54000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f0ad58d0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0ad73c0000)
[root@c21dbc793d27 /]# ldd /usr/local/lib/libcurl.so.4
        linux-vdso.so.1 =>  (0x00007ffe72389000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f84f5fd4000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f84f5dcc000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f84f5bc8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f84f59ab000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f84f5617000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f84f66c9000)
```

```
[root@c21dbc793d27 /]# ldd /usr/lib64/libcurl.so.4
        linux-vdso.so.1 =>  (0x00007ffecac9b000)
        libidn.so.11 => /lib64/libidn.so.11 (0x00007f83bcdd4000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f83bcb83000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f83bc97b000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f83bc737000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f83bc450000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f83bc224000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f83bc020000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f83bbe0a000)
        libssl3.so => /usr/lib64/libssl3.so (0x00007f83bbbb7000)
        libsmime3.so => /usr/lib64/libsmime3.so (0x00007f83bb98a000)
        libnss3.so => /usr/lib64/libnss3.so (0x00007f83bb642000)
        libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007f83bb413000)
        libplds4.so => /lib64/libplds4.so (0x00007f83bb20f000)
        libplc4.so => /lib64/libplc4.so (0x00007f83bb00a000)
        libnspr4.so => /lib64/libnspr4.so (0x00007f83badcb000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f83babae000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f83ba9aa000)
        libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007f83ba782000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f83ba3ee000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f83ba1df000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f83b9fc5000)
        libsasl2.so.2 => /usr/lib64/libsasl2.so.2 (0x00007f83b9dab000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f83bd25b000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f83b9ba0000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f83b999d000)
        libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f83b9731000)
        libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f83b934c000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f83b9115000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f83b8ef6000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f83b8cf3000)
```

**Comment by levyfan** [comment]
This error happens when we trying to install yum-utils and use yum-config-manager.

**Comment by mayeut** [comment]
There's no issue in the manylinux2010_x86_64 image. The file /usr/local/lib/libcurl.so.4 does not exist anymore it was removed in commit ec22d4a446eb64aa180b39b0d7901bd663829bc3:
``` 
Matt$ docker run --rm -it quay.io/pypa/manylinux2010_x86_64:latest python -c 'import yum; print(yum.__version__)'
3.2.29
Matt$ docker run --rm -it quay.io/pypa/manylinux2010_x86_64:latest ldd /usr/lib64/python2.6/site-packages/pycurl.so
	linux-vdso.so.1 =>  (0x00007fffaebf3000)
	libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007ff09e9f6000)
	libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x00007ff09e650000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff09e433000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff09e09f000)
	libidn.so.11 => /lib64/libidn.so.11 (0x00007ff09de6d000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007ff09dc1c000)
	librt.so.1 => /lib64/librt.so.1 (0x00007ff09da14000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007ff09d7d0000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007ff09d4e9000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007ff09d2bd000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007ff09d0b9000)
	libz.so.1 => /lib64/libz.so.1 (0x00007ff09cea3000)
	libssl3.so => /usr/lib64/libssl3.so (0x00007ff09cc4a000)
	libsmime3.so => /usr/lib64/libsmime3.so (0x00007ff09ca1d000)
	libnss3.so => /usr/lib64/libnss3.so (0x00007ff09c6d5000)
	libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007ff09c4a5000)
	libplds4.so => /lib64/libplds4.so (0x00007ff09c2a1000)
	libplc4.so => /lib64/libplc4.so (0x00007ff09c09c000)
	libnspr4.so => /lib64/libnspr4.so (0x00007ff09be5e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff09bc5a000)
	libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007ff09ba32000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007ff09b82f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff09b5ab000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff09ee5c000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007ff09b39c000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007ff09b182000)
	libsasl2.so.2 => /usr/lib64/libsasl2.so.2 (0x00007ff09af68000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007ff09ad5d000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007ff09ab5a000)
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007ff09a8ee000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007ff09a509000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007ff09a2d2000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007ff09a0b3000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007ff099eb0000)
```

Installing `yum-utils` doesn't change the outcome:
```
Matt$ docker run --rm -it quay.io/pypa/manylinux2010_x86_64:latest /bin/bash 
[root@0cd309b55055 /]# yum install -y yum-utils
Loaded plugins: fastestmirror, ovl
Setting up Install Process
Determining fastest mirrors
epel/metalink                                                                                                                                                                          |  31 kB     00:00     
 * base: centos.mirror.ate.info
 * centos-sclo-rh: centos.mirror.ate.info
 * centos-sclo-sclo: centos.quelquesmots.fr
 * epel: epel.uni-sofia.bg
 * extras: centos.mirror.ate.info
 * updates: centos.mirror.ate.info
base                                                                                                                                                                                   | 3.7 kB     00:00     
base/primary_db                                                                                                                                                                        | 4.7 MB     00:05     
centos-sclo-rh                                                                                                                                                                         | 3.0 kB     00:00     
centos-sclo-rh/primary_db                                                                                                                                                              | 1.5 MB     00:01     
centos-sclo-sclo                                                                                                                                                                       | 2.9 kB     00:00     
centos-sclo-sclo/primary_db                                                                                                                                                            | 166 kB     00:00     
epel                                                                                                                                                                                   | 4.7 kB     00:00     
epel/primary_db                                                                                                                                                                        | 6.1 MB     00:06     
extras                                                                                                                                                                                 | 3.4 kB     00:00     
extras/primary_db                                                                                                                                                                      |  29 kB     00:00     
updates                                                                                                                                                                                | 3.4 kB     00:00     
updates/primary_db                                                                                                                                                                     | 9.4 MB     00:07     
Resolving Dependencies
--> Running transaction check
---> Package yum-utils.noarch 0:1.1.30-42.el6_10 will be installed
--> Processing Dependency: libxml2-python for package: yum-utils-1.1.30-42.el6_10.noarch
--> Running transaction check
---> Package libxml2-python.x86_64 0:2.7.6-21.el6_8.1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================================
 Package                                              Arch                                         Version                                                Repository                                     Size
==============================================================================================================================================================================================================
Installing:
 yum-utils                                            noarch                                       1.1.30-42.el6_10                                       updates                                       114 k
Installing for dependencies:
 libxml2-python                                       x86_64                                       2.7.6-21.el6_8.1                                       base                                          325 k

Transaction Summary
==============================================================================================================================================================================================================
Install       2 Package(s)

Total download size: 439 k
Installed size: 2.2 M
Downloading Packages:
(1/2): libxml2-python-2.7.6-21.el6_8.1.x86_64.rpm                                                                                                                                      | 325 kB     00:00     
(2/2): yum-utils-1.1.30-42.el6_10.noarch.rpm                                                                                                                                           | 114 kB     00:00     
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                         815 kB/s | 439 kB     00:00     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : libxml2-python-2.7.6-21.el6_8.1.x86_64                                                                                                                                                     1/2 
  Installing : yum-utils-1.1.30-42.el6_10.noarch                                                                                                                                                          2/2 
  Verifying  : yum-utils-1.1.30-42.el6_10.noarch                                                                                                                                                          1/2 
  Verifying  : libxml2-python-2.7.6-21.el6_8.1.x86_64                                                                                                                                                     2/2 

Installed:
  yum-utils.noarch 0:1.1.30-42.el6_10                                                                                                                                                                         

Dependency Installed:
  libxml2-python.x86_64 0:2.7.6-21.el6_8.1                                                                                                                                                                    

Complete!
[root@0cd309b55055 /]# python -c 'import yum; print(yum.__version__)'
3.2.29
[root@0cd309b55055 /]# ldd /usr/lib64/python2.6/site-packages/pycurl.so
	linux-vdso.so.1 =>  (0x00007ffdf64aa000)
	libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007fc9da228000)
	libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x00007fc9d9e82000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc9d9c65000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc9d98d1000)
	libidn.so.11 => /lib64/libidn.so.11 (0x00007fc9d969f000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007fc9d944e000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc9d9246000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fc9d9002000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fc9d8d1b000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fc9d8aef000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fc9d88eb000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc9d86d5000)
	libssl3.so => /usr/lib64/libssl3.so (0x00007fc9d847c000)
	libsmime3.so => /usr/lib64/libsmime3.so (0x00007fc9d824f000)
	libnss3.so => /usr/lib64/libnss3.so (0x00007fc9d7f07000)
	libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007fc9d7cd7000)
	libplds4.so => /lib64/libplds4.so (0x00007fc9d7ad3000)
	libplc4.so => /lib64/libplc4.so (0x00007fc9d78ce000)
	libnspr4.so => /lib64/libnspr4.so (0x00007fc9d7690000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc9d748c000)
	libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007fc9d7264000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fc9d7061000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc9d6ddd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc9da68e000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007fc9d6bce000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fc9d69b4000)
	libsasl2.so.2 => /usr/lib64/libsasl2.so.2 (0x00007fc9d679a000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fc9d658f000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fc9d638c000)
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007fc9d6120000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007fc9d5d3b000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fc9d5b04000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fc9d58e5000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007fc9d56e2000)
[root@0cd309b55055 /]# ldd /usr/local/lib/libcurl.so.4
ldd: /usr/local/lib/libcurl.so.4: No such file or directory
[root@0cd309b55055 /]# 
```
