### ISSUE TITLE
Need to update wheel for auditwheel 3.1.0

### ISSUE THREAD

**Issue by manthey** [pypa/manylinux#512]
Auditwheel 3.1.0 requires a newer version of wheel than is in the current docker image.  Specifically, I see an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 8, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/main.py", line 50, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/main_repair.py", line 49, in execute
    from .repair import repair_wheel
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/repair.py", line 14, in <module>
    from .wheeltools import InWheelCtx, add_platforms
  File "/opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/auditwheel/wheeltools.py", line 17, in <module>
    from wheel.wheelfile import WHEEL_INFO_RE  # type: ignore
ModuleNotFoundError: No module named 'wheel.wheelfile'
```

**Comment by MuellerSeb** [comment]
This line needs to be updated to `wheel==0.34.2`:
https://github.com/pypa/manylinux/blob/f878e29fe8b81a2921807cb9e299c941c1ed37ea/docker/build_scripts/py37-requirements.txt#L11

**Comment by MuellerSeb** [comment]
The PR is already created:
https://github.com/pypa/manylinux/pull/469

**Comment by MuellerSeb** [comment]
Should be done with: https://github.com/pypa/manylinux/commit/a2d83911f4bc8b35dbf34a90ce552c71daee0ef1

**Comment by manthey** [comment]
Thanks.  The manylinux2010 docker is working again.

**Comment by mayeut** [comment]
Thanks for all the feedback.
